"""Add file_path to YogaProgram

Revision ID: 170241bf31c5
Revises: 
Create Date: 2024-11-09 00:21:41.716154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170241bf31c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoga_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoga_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.BLOB(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
